using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class StopperObject : MonoBehaviour
{
    [SerializeField, Tooltip("ÚG”»’è‚ğs‚¤Collider")]
    private Collider _knifeCollider = default;

    private void Update()
    {
        // ÚG‚µ‚½Collider‚ğ”»’è‚µ‚ÄŠi”[‚·‚é
        Collider[] hitColliders = Physics.OverlapBox(_knifeCollider.bounds.center, _knifeCollider.bounds.size, this.transform.rotation);

        // ÚG‚µ‚½Collider‚ª‚È‚©‚Á‚½ê‡
        if (hitColliders is null)
        {
            // ‚È‚É‚à‚µ‚È‚¢
            Debug.Log($"‚È‚É‚à“–‚½‚Á‚Ä‚È‚¢‚æ‚ñ");
            return;
        }

        // ÚG‚µ‚½Collider‚·‚×‚Ä‚É”»’è‚ğs‚¤
        foreach (Collider hitCollider in hitColliders)
        {
            // Stoppable‚ğ‚Á‚Ä‚¢‚È‚¢ê‡
            if (!hitCollider.transform.root.TryGetComponent<Stoppable>(out var stoppable))
            {
                // Ÿ‚ÌCollider‚Ö
                continue;
            }

            // StopData‚ğ‚Á‚Ä‚¢‚éê‡
            if (hitCollider.transform.root.TryGetComponent<StopData>(out var stopData))
            {
                // StopData‚Ì’â~ƒtƒ‰ƒO‚ğ—§‚Ä‚é
                stopData.StopEnd(true);
            }
            // StopData‚ğ‚Á‚Ä‚¢‚È‚¢ê‡
            else
            {
                // ÚG‚µ‚Ä‚¢‚éƒIƒuƒWƒFƒNƒg‚ÉStopData‚ğ‰Á‚¦‚é
                hitCollider.transform.root.gameObject.AddComponent<StopData>();

                // ’â~‚Ìˆ—‚ğÀs‚·‚é
                stoppable.StoppingEvent();
            }
        }
    }
}
